### ISSUE TITLE
zet je code (zo snel mogelijk) in een subfolder

### ISSUE THREAD

**Issue by stgm** [mischahondius/equicam_android#1]

**Comment by mischahondius** [comment]
Hi Martijn,

Snap niet helemaal wat je hiermee bedoelt?

Mischa

2015-06-03 11:17 GMT+02:00 Martijn Stegeman notifications@github.com:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/mischahondius/equicam_android/issues/1.

## 

Kind regards, met vriendelijke groet,

_Mischa Hondius_
EQuifilm

Tel. +31 (0)6 539 346 93

KVK: 50075993
BTW: NL201237234B02

www.mischahondius.nl
info@mischahondius.nl

http://nl.linkedin.com/in/mischahondius
http://www.twitter.com/mischahondius
http://www.youtube.com/mischahondius

**Comment by stgm** [comment]
Vraag morgen maar even.
